# Get short (7-digit) commit hash
execute_process(
  COMMAND git rev-parse --short=7 HEAD
  WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
  OUTPUT_VARIABLE GIT_COMMIT
  OUTPUT_STRIP_TRAILING_WHITESPACE
)

get_filename_component(VERSION_TAG_PATH "version.tag" ABSOLUTE)
if(EXISTS ${VERSION_TAG_PATH})
    file(READ version.tag VERSION_TAG OFFSET 1)
  string(REPLACE "." ";" VERSION_LIST ${VERSION_TAG})
  list(GET VERSION_LIST 0 APP_VERSION_MAJOR)
  list(GET VERSION_LIST 1 APP_VERSION_MINOR)
  list(GET VERSION_LIST 2 APP_VERSION_PATCH)
  list(GET VERSION_LIST 3 APP_VERSION_TAG)
else()
  set(APP_VERSION_MAJOR 0)
  set(APP_VERSION_MINOR 0)
  set(APP_VERSION_PATCH 0)
  set(APP_VERSION_TAG "${GIT_COMMIT}")
endif()

set(FILE_VERSION "${APP_VERSION_MAJOR}.${APP_VERSION_MINOR}.${APP_VERSION_PATCH}+${APP_VERSION_TAG}")
MESSAGE( STATUS "VERSION MAJOR: " ${APP_VERSION_MAJOR} )
MESSAGE( STATUS "VERSION MINOR: " ${APP_VERSION_MINOR} )
MESSAGE( STATUS "VERSION PATCH: " ${APP_VERSION_PATCH} )
MESSAGE( STATUS "VERSION TAG: " ${APP_VERSION_TAG} )

configure_file (
  "${CMAKE_CURRENT_SOURCE_DIR}/src/app_version.h.in"
  "${CMAKE_CURRENT_BINARY_DIR}/app_version.h"
)
